Controllers films users
LapshYP/java-filmorate pull request #2
Opened 2023-03-21 16:48 UTC by LapshYP

Добрый вечер!
прошу проверить тз №9.

2023-03-22 16:17 UTC, z8q requested changes

2023-03-22 16:17 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<String, String> handleValidationExceptions(MethodArgumentNotValidException ex) {
Методы, которые отлавливают исключения лучше выделять в отдельный класс

2023-03-22 16:17 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +        if (user.getName() == null || user.getName().equals("")) {
Если name будет состоять только из пробелов – `"   "`, проверка не сработает

2023-03-22 16:17 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +    public @Valid Film addFilms(@Valid Film film) {
Не совсем понимаю, зачем тут `@Valid`-ы ставить.
Мы принимаем провалидированный фильм с контроллера, и его же возвращаем

2023-03-22 16:17 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        @Valid Film filmToUpdate = filmServiceImpl.updateFilm(film);
Тут тоже `@Valid` можно убрать.
Даже если представить, что положим мы не так заполним поля на бэке.
Мы вернем пользователю сообщение об ошибке, что неправильно заполнили поля?)

2023-03-22 16:17 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserServiceImpl userServiceImpl = new UserServiceImpl();
Тоже лучше задавать значение через конструктор

2023-03-22 16:17 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Map<String, String> handleValidationExceptions(MethodArgumentNotValidException ex) {
По методу с исключением и `@Valid`-ы – то же самое, что в film controller

2023-03-22 16:17 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    int rate;
В тз нет информации про rate:
- целочисленный идентификатор — `id`;
- название — `name`;
- описание — `description`;
- дата релиза — `releaseDate`;
- продолжительность фильма — `duration`.

2023-03-22 16:17 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Builder
Builder используется?

2023-03-22 18:39 UTC, LapshYP commented on pom.xml
> +<!--				<artifactId>spring-boot-maven-plugin</artifactId>-->
> Закомментированный код лучше убрать

удалил

2023-03-22 18:51 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmServiceImpl filmServiceImpl = new FilmServiceImpl();
> Лучше инджект зависимости делать через конструктор. И над конструктором ставить @Autowired Нужно для поля явно поставить модификатор доступа private/public/protected
добавил конструктор

2023-03-22 18:55 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        @Valid Film filmToAdd = filmServiceImpl.addFilms(film);
> `@Valid` тут не нужен, если мы получаем тот же объект, который принимаем в аргументах в 37-й строке



> `@Valid` тут не нужен, если мы получаем тот же объект, который принимаем в аргументах в 37-й строке
удалил
эту аннотацию автоматически Идея подставила, по нажатию контл+шифт +v

2023-03-22 18:56 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        @Valid Film filmToAdd = filmServiceImpl.addFilms(film);
удалил
эту аннотацию автоматически Идея подставила, по нажатию контл+шифт +v

2023-03-23 02:12 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        @Valid Film filmToUpdate = filmServiceImpl.updateFilm(film);
убрал

2023-03-23 02:13 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserServiceImpl userServiceImpl = new UserServiceImpl();
поменял

2023-03-23 02:14 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Map<String, String> handleValidationExceptions(MethodArgumentNotValidException ex) {
удалил аннотации

2023-03-23 02:18 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    int rate;
удалил , но в условии есть:
"Вы напишете бэкенд для сервиса, который будет работать с фильмами и оценками пользователей, а также возвращать топ-5 фильмов, рекомендованных к просмотру. "
и поле rate было в тестах постмана

2023-03-23 02:33 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Builder
Добавил использование User.builder() в классе UserControllerTest

2023-03-23 21:00 UTC, closed without merging