Add friends likes
LapshYP/java-filmorate pull request #4
Opened 2023-04-05 20:07 UTC by LapshYP

тз 10 на проверку

2023-04-07 18:57 UTC, z8q requested changes

2023-04-07 18:57 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/exception/ControllerExceptionHandler.java
> +        return Map.of("not found exception - ", ex.getMessage());
В handleValidationExceptions можно понять, почему собираем мапу.
Но есть ли смысл собирать мапу тут, когда у нас одно значение

2023-04-07 18:57 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorageImpl.java
> +    private HashMap<Integer, Film> filmStore = new HashMap<>();
final

2023-04-07 18:57 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Integer> likes = new TreeSet<>();
Зачем TreeSet? Не совсем понимаю, зачем нам сортировать лайки

2023-04-07 18:57 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        filmToUpdate.setLikes(likes);
Попробуй закомментировать 70-ю строку
Лайки все равно будут сохранятся при добавлении в 69-й строке

2023-04-07 18:57 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Builder.Default
С этой аннотацией интересно.
Если мы отправим на контроллер сохранить такого user-а:
{
	"email": "bob@yandex.ru",
	"login": "bob_user",
	"name": "bob",
	"birthday": "2011-11-11"
}

То у нас поле friends сохранится как null. После чего мы можем поймать nullPointerException при добавлении друзей.
Без аннотации сохраняется просто пустой список.

2023-04-07 18:57 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorageImpl.java
> +        System.out.println("");
Для чего используем system.out?

2023-04-07 18:57 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
>          } else if (userToUpdate.getName() == null || userToUpdate.getName().equals("")) {
Если имя будет состоять только из пробелов, в базу сохранятся пробелы

2023-04-07 18:57 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +                .stream()
stream перед foreach нет необходимости ставить

2023-04-09 04:10 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        List<Film> collect = filmServiceImpl
упростил

2023-04-09 04:15 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        List<User> userList = userServiceImpl.getAllUsers().values().stream().collect(Collectors.toList());
упростил

2023-04-09 04:17 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorageImpl.java
> +    private HashMap<Integer, Film> filmStore = new HashMap<>();
поправил

2023-04-09 04:20 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Integer> likes = new TreeSet<>();
поправил на new HashSet<>();

2023-04-09 04:25 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        filmToUpdate.setLikes(likes);
закоментировал,
думал что данные копируются, а оказывается - ссылаются

2023-04-09 04:28 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Builder.Default
удалил анотацию

2023-04-09 04:37 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
>          } else if (userToUpdate.getName() == null || userToUpdate.getName().equals("")) {
добавил проверку на имена из пробелов

2023-04-09 07:34 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +                .stream()
удалил   .stream()

2023-04-10 12:53 UTC, z8q approved these changes

2023-04-22 08:00 UTC, merged