Add database
LapshYP/java-filmorate pull request #6
Opened 2023-05-03 18:50 UTC by LapshYP

Тз11 на проверку

2023-05-04 19:36 UTC, z8q requested changes

2023-05-04 19:36 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public @Valid User addUser(@Valid @RequestBody User user) {
Допускается добавление дублей пользователей. Стоит проверять email и логин на уникальность.

Если в body не укажем email, придет ошибка стороне сервера:
{
	"timestamp": "2023-05-04T19:06:19.856+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/users/"
}
Тоже не очень хорошо

2023-05-04 19:36 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User addFriends(@PathVariable int userId, @PathVariable int friendId) {
PUT http://localhost:8080/users/1123/friends/1
Пользователь 1 существует
1123 не существует

Но запись в базе все равно сохранится

Повторные запросы с теми же id продолжают сохранятся в базу

2023-05-04 19:36 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User removeFriends(@PathVariable int userId, @PathVariable int friendId) {
Первый раз удаляет.
При повторных запросах продолжает присылать ответ 200. Хотя пользователи уже не друзья

2023-05-04 19:36 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film addLike(@PathVariable int filmId, @PathVariable int userId) {
Допускается несколько раз поставить лайк от одного пользователя одному и тому же фильму

2023-05-04 19:36 UTC, z8q commented on src/main/resources/dbschema.png
Отношение mpa к films – один ко многим.
Это значит, что было бы правильно внутри films добавить foreign key mpa_id.
А табличку mpa составить только из mpa_id и mpa_name.
Если использовать текущую реализацию, в таблице mpa будет много записей с одинаковыми mpa_name на каждый фильм.

В likes было бы достаточно полей film_id и user_id, так как комбинация этих двух полей уникальна. Не может быть например двух одинаковых записей с film_id = 1 и user_id = 2. Дополнительное поле like_id не требуется.

Аналогично с friendships

2023-05-07 12:31 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film addFilm(@Valid @RequestBody Film film) {
Добрый день! спасибо за замечания, вроде бы все поправил.

2023-05-07 12:31 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public @Valid User addUser(@Valid @RequestBody User user) {
внес изменения чтобы проверялось наличие email

2023-05-07 12:32 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User addFriends(@PathVariable int userId, @PathVariable int friendId) {
добавил проверку пользователей указанных в запрсе

2023-05-07 12:33 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User removeFriends(@PathVariable int userId, @PathVariable int friendId) {
добавил при повторном удаление сообщение и статус

2023-05-07 12:33 UTC, LapshYP commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film addLike(@PathVariable int filmId, @PathVariable int userId) {
добавил, что при повторном запросе должно выдаваться сообщение что лайк уже стоит

2023-05-07 12:33 UTC, LapshYP commented on src/main/resources/dbschema.png
поправил связи с таблицами

2023-05-08 19:24 UTC, z8q requested changes

2023-05-08 19:24 UTC, z8q commented on README.md
> +Ссылка на структуру базы данных [dbdiagram.io](https://dbdiagram.io/d/644378a96b31947051028cb1)
Картинку только тоже нужно поправить.
Таблицы вижу, что приведены в норму

2023-05-09 19:01 UTC, z8q approved these changes

2023-05-28 15:30 UTC, merged